/**
 * Small UI sounds, played from audio files: a cafe door bell when entering, a
 * service-bell "ting" for incoming messages and a spoon-on-cup tap when
 * sending, and a thank-you voice clip once a reservation is made. The .wav
 * files in resources/audio are generated by scripts/generate-sounds.mjs
 * (`npm run sounds`); thank-you.mp3 is a recording, trimmed to 5 seconds.
 * Sound only ever follows a guest action, never plays on its own, and can be
 * muted with the header toggle (remembered per browser).
 */
import enterUrl from '../audio/enter.wav';
import incomingUrl from '../audio/incoming.wav';
import sentUrl from '../audio/sent.wav';
import thankYouUrl from '../audio/thank-you.mp3';

const STORAGE_KEY = 'cafe_sound';
const VOLUME = 0.6;

const sources = {
    enter: enterUrl,
    incoming: incomingUrl,
    sent: sentUrl,
    thanks: thankYouUrl,
};

const clips = {};

function isEnabled() {
    try {
        return localStorage.getItem(STORAGE_KEY) !== 'off';
    } catch {
        return true;
    }
}

/** Fetch the files once the page is up, so the first sound is not late. */
function preload() {
    for (const [name, url] of Object.entries(sources)) {
        const clip = new Audio(url);
        clip.preload = 'auto';
        clips[name] = clip;
    }
}

function play(name) {
    if (!isEnabled() || !clips[name]) return;

    try {
        // A clone per play lets quick repeats overlap instead of cutting off.
        const clip = clips[name].cloneNode();
        clip.volume = VOLUME;
        clip.play().catch(() => {});
    } catch {
        /* audio unavailable: the interface works the same without it */
    }
}

function syncToggles() {
    const enabled = isEnabled();

    document.querySelectorAll('[data-sound-toggle]').forEach((button) => {
        button.setAttribute('aria-pressed', String(enabled));
        button.setAttribute('aria-label', enabled ? button.dataset.labelOn : button.dataset.labelOff);
        button.classList.toggle('is-muted', !enabled);
    });
}

function initSoundToggle() {
    preload();
    syncToggles();

    document.querySelectorAll('[data-sound-toggle]').forEach((button) => {
        button.addEventListener('click', () => {
            try {
                localStorage.setItem(STORAGE_KEY, isEnabled() ? 'off' : 'on');
            } catch { /* preference just won't persist */ }

            syncToggles();
            play('sent');
        });
    });
}

window.cafeSound = { play, isEnabled };

document.addEventListener('DOMContentLoaded', initSoundToggle);
