<?php

namespace App\Modules\Experience\Presenters;

/**
 * The guest-facing words of the stage, per language. Every sentence lives in
 * lang/<locale>/stage.php; nothing here is generated by the model.
 */
final class StageCopy
{
    /**
     * What the AI Barista says when the guest steps into a scene.
     *
     * @return array<string, string>
     */
    public static function narration(string $locale): array
    {
        return trans('stage.narration', [], $locale);
    }

    /**
     * Guest-facing names for the coded values stored in the database.
     *
     * @return array<string, array<string, string>>
     */
    public static function terms(string $locale): array
    {
        return trans('stage.terms', [], $locale);
    }

    /**
     * Navigation, chat and reservation-summary labels.
     *
     * @return array<string, string>
     */
    public static function labels(string $locale): array
    {
        return trans('stage.labels', [], $locale);
    }

    /**
     * Headings and notes of the stage scenes.
     *
     * @return array<string, string>
     */
    public static function copy(string $locale): array
    {
        return trans('stage.copy', [], $locale);
    }

    /**
     * The reservation wizard's labels, with the guest-facing validation
     * messages it shows beside a field.
     *
     * @return array<string, mixed>
     */
    public static function wizard(string $locale): array
    {
        return [...trans('reservation.messages', [], $locale), ...trans('stage.wizard', [], $locale)];
    }

    /**
     * The cafe picker's labels.
     *
     * @return array<string, string>
     */
    public static function opening(string $locale): array
    {
        return trans('stage.opening', [], $locale);
    }
}
